#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &

# Set wallpaper
xloadimage -onroot -zoom 75 "$HOME/images/wallpaper.jpg"

# Start two terminals
gnome-terminal &
gnome-terminal &

# disable touchpad while typing
syndaemon -d -i 1

# Preload dmenu
dmenu &

# remap Caps-Lock to Control and start xcape
setxkbmap us_intl
xmodmap ~/.xmodmap
xcape

pulseaudio --start &

exec xmonad
